// Integration tests: the snapshot suite over the scores that travel with the repository, plus
// the fixture.mscz checks of the extraction pipeline.
//
// The scores in test/its/scores/ are synthetic, written by the build-*.js generator beside each
// one, and committed: they are the fixtures of record, and each exists to reach code the others
// do not. test/its/snapshot.js drives them, discovering what to run from the baselines present.
//
// A developer who keeps frozen copies of real scores puts them, with their own baselines, in
// test/local/ together with a test file of their own. That folder is ignored by git and picked
// up by "npm test" when it is there, so nothing about those scores appears in this repository.
var test = require("node:test");
var assert = require("node:assert/strict");
var path = require("path");
var fs = require("fs");
var child = require("child_process");
var msczReader = require("../score/mscz-reader");
var xmlExtractor = require("../score/xml-extractor");
var orchestrator = require("../lib/orchestrator");
var chordUtils = require("../lib/chord-utils");

var FIXTURE_PATH = path.join(__dirname, "fixture.mscz");
var BASE = path.resolve(__dirname, "..");
// LE_CLI points the snapshot tests at another copy of the CLI, which is how
// "npm run test:package" runs them against the minified staging tree: same scores, same
// baselines, so a minification that changes any output fails here.
var CLI = process.env.LE_CLI ? path.resolve(process.env.LE_CLI) : path.join(BASE, "cli/index.js");
var ITS_DIR = path.join(__dirname, "its");

var synthetic = require("./its/synthetic");
var snapshot = require("./its/snapshot");

// ============================================================
// Snapshot tests: compare CLI output against baseline .txt files
// ============================================================

snapshot.define({
    baselinesDir: ITS_DIR,
    cli: CLI,
    note: function(song) {
        var generator = synthetic.SYNTHETIC[song];
        if (!generator) return null;
        // Committed score, so its mtime is whenever the checkout happened and comparing it
        // against the marker would mean nothing
        return "NOTE: this score is generated by test/its/" + generator +
            " and committed with the repository.\n  Either the output changed for a real reason," +
            " or the score and its generator have drifted:\n    node --test test/synthetic-scores.test.js";
    }
});

// ============================================================
// fixture.mscz tests: data extraction and pipeline validation
// ============================================================

test("integration: fixture.mscz reads and extracts correctly", function() {
    var xml = msczReader.readScore(FIXTURE_PATH);
    assert.ok(xml.length > 100, "XML should be substantial");
    assert.ok(xml.indexOf("<museScore") >= 0, "Should contain museScore root element");
    assert.ok(xml.indexOf("<Score") >= 0, "Should contain Score element");
});

test("integration: fixture.mscz spelling detection", function() {
    var spelling = msczReader.readSpelling(FIXTURE_PATH);
    assert.equal(spelling, "solfeggio", "fixture has solfeo spelling in score_style.mss");
});

test("integration: fixture.mscz data structure integrity", function() {
    var xml = msczReader.readScore(FIXTURE_PATH);
    var spelling = msczReader.readSpelling(FIXTURE_PATH);
    var data = xmlExtractor.extractAll(xml, [], spelling);

    assert.ok(data.syllables.length >= 3, "Should have syllables");
    assert.ok(data.chords.length >= 2, "Should have chords");
    assert.equal(data.repeats.length, 1, "Should have 1 repeat");

    for (var i = 0; i < data.syllables.length; i++) {
        var s = data.syllables[i];
        assert.ok(typeof s.tick === "number", "syllable should have tick");
        assert.ok(typeof s.verse === "number", "syllable should have verse");
        assert.ok(typeof s.text === "string" && s.text.length > 0, "syllable should have text");
        assert.ok(["single", "begin", "end", "middle"].indexOf(s.syllabic) >= 0, "syllable should have valid syllabic");
    }

    for (var j = 0; j < data.chords.length; j++) {
        var c = data.chords[j];
        assert.ok(typeof c.tick === "number", "chord should have tick");
        assert.ok(typeof c.chord === "string" && c.chord.length > 0, "chord should have chord name");
    }
});

test("integration: fixture.mscz produces solfeo chord names", function() {
    var xml = msczReader.readScore(FIXTURE_PATH);
    var spelling = msczReader.readSpelling(FIXTURE_PATH);
    var data = xmlExtractor.extractAll(xml, [], spelling);

    assert.equal(data.chords[0].chord, "Lam", "first chord should be Lam (solfeo)");
    assert.equal(data.chords[1].chord, "Mi7", "second chord should be Mi7 (solfeo)");
    assert.equal(data.chords[2].chord, "La", "third chord should be La (solfeo)");
});

test("integration: fixture.mscz produces anglo chord names with standard spelling", function() {
    var xml = msczReader.readScore(FIXTURE_PATH);
    var data = xmlExtractor.extractAll(xml, [], "standard");

    assert.equal(data.chords[0].chord, "Am", "first chord should be Am (anglo)");
    assert.equal(data.chords[1].chord, "E7", "second chord should be E7 (anglo)");
    assert.equal(data.chords[2].chord, "A", "third chord should be A (anglo)");
});

test("integration: fixture.mscz orchestrator produces output", function() {
    var xml = msczReader.readScore(FIXTURE_PATH);
    var spelling = msczReader.readSpelling(FIXTURE_PATH);
    var data = xmlExtractor.extractAll(xml, [], spelling);
    var output = orchestrator.processExtraction(data);

    assert.ok(output, "Should produce output");
    assert.ok(output.indexOf("TEST FIXTURE") >= 0, "Should contain title");
    assert.ok(output.indexOf("Mi7") >= 0, "Should contain solfeo chord Mi7");
    assert.ok(output.indexOf("Hel") >= 0, "Should contain lyrics");
});

test("integration: tpcToChordName handles literal text without root", function() {
    var Constants = require("../lib/constants");
    assert.equal(Constants.tpcToChordName(-99, "Bajos", "solfeggio"), "Bajos");
    assert.equal(Constants.tpcToChordName(-99, "Rem", "standard"), "Rem");
    assert.equal(Constants.tpcToChordName(-99, "", "solfeggio"), "");
});

test("integration: readSpelling returns standard when no style sheet", function() {
    var spelling = msczReader.readSpelling("/tmp/nonexistent.mscx");
    assert.equal(spelling, "standard");
});

test("integration: trailing chords appended to last line are not duplicated as coda", function() {
    var data = {
        title: "TEST",
        syllables: [
            { tick: 0, verse: 0, text: "ho", syllabic: "begin", durationQ: 1 },
            { tick: 480, verse: 0, text: "la.", syllabic: "end", durationQ: 1 }
        ],
        chords: [
            { tick: 0, chord: "Do" },
            { tick: 600, chord: "Sol" },
            { tick: 800, chord: "Do" },
            { tick: 1000, chord: "Sol" },
            { tick: 1200, chord: "Do" }
        ],
        repeats: [], voltas: [], markers: [], jumps: [],
        systemTexts: [], barlines: [], lastTick: 1500, division: 480
    };
    var output = orchestrator.processExtraction(data);
    var solCount = (output.match(/\bSol\b/g) || []).length;
    var doCount = (output.match(/\bDo\b/g) || []).length;
    assert.equal(solCount, 2, "Sol should appear exactly twice (in trailing): " + output);
    assert.equal(doCount, 3, "Do should appear exactly three times (1 inline + 2 trailing): " + output);
});
